### ISSUE TITLE
plugin.json issues

### ISSUE THREAD

**Issue by cschol** [salvolm84/SLM-vcv-rack#2]
The plugin manifest validation script found the following issues:

```
Validating SLM-vcv-rack
pluginUrl: no URL specified
authorUrl: no URL specified
```

**At least** `pluginUrl` needs to be set to the README.md of the Github repository.

**Comment by salvolm84** [comment]
fixed in 327f3f56fd1913cdf1164bd9e10215882234c6f8
BTW I thought those fields were both optional as in https://github.com/VCVRack/library/tree/master/manifests I saw some of them have blank author/plugin URLs and I guess they passed review.
Maybe the validation script has been updated in between.
