### ISSUE TITLE
Can you make an 8 channel version of Muxfreak?

### ISSUE THREAD

**Issue by 77377** [salvolm84/SLM-vcv-rack#3]
Hi, love muxfreak, it's a well executed concept and pretty musical. I'd only wish there would be an 8 channel version of it, since I use muxfreak as sort of a propabilistic sequencer, feeding constant voltages into it, works great btw. and it would even better if we got 8 ins. 
Cheers!

**Comment by salvolm84** [comment]
Hi, glad to know you like this module!
Making a 8 channels version is pretty easy and I will definitely add it to the next SLM plugin release
Cheers
